import EstateBuilding from './assets/estate.svg';

export const dataProperties = [
	{
		name: 'NAME NAME',
		image: EstateBuilding,
		minInVestment: '20 Lakhs',
		minArea: '100 sq.ft.',
		rentalYield: '9%-12%',
		location: 'Sector 121, Noida',
	},
	{
		name: 'NAME NAME',
		image: EstateBuilding,
		minInVestment: '20 Lakhs',
		minArea: '100 sq.ft.',
		rentalYield: '9%-12%',
		location: 'Sector 121, Noida',
	},
	{
		name: 'NAME NAME',
		image: EstateBuilding,
		minInVestment: '20 Lakhs',
		minArea: '100 sq.ft.',
		rentalYield: '9%-12%',
		location: 'Sector 121, Noida',
	},
	{
		name: 'NAME NAME',
		image: EstateBuilding,
		minInVestment: '20 Lakhs',
		minArea: '100 sq.ft.',
		rentalYield: '9%-12%',
		location: 'Sector 121, Noida',
	},
	{
		name: 'NAME NAME',
		image: EstateBuilding,
		minInVestment: '20 Lakhs',
		minArea: '100 sq.ft.',
		rentalYield: '9%-12%',
		location: 'Sector 121, Noida',
	},
	{
		name: 'NAME NAME',
		image: EstateBuilding,
		minInVestment: '20 Lakhs',
		minArea: '100 sq.ft.',
		rentalYield: '9%-12%',
		location: 'Sector 121, Noida',
	},
	{
		name: 'NAME NAME',
		image: EstateBuilding,
		minInVestment: '20 Lakhs',
		minArea: '100 sq.ft.',
		rentalYield: '9%-12%',
		location: 'Sector 121, Noida',
	},
	{
		name: 'NAME NAME',
		image: EstateBuilding,
		minInVestment: '20 Lakhs',
		minArea: '100 sq.ft.',
		rentalYield: '9%-12%',
		location: 'Sector 121, Noida',
	},
	{
		name: 'NAME NAME',
		image: EstateBuilding,
		minInVestment: '20 Lakhs',
		minArea: '100 sq.ft.',
		rentalYield: '9%-12%',
		location: 'Sector 121, Noida',
	},
];
